#!/bin/bash
pidtree() (
    declare -A CHILDS
    declare -A COMMANDS
    while read P PP COMMAND;do
        CHILDS[$PP]+=" $P"
        COMMANDS[$P]="$COMMAND"
    done < <(ps -e -o pid= -o ppid= -o comm=)

    walk() {
        echo $1 ${COMMANDS[$1]}
        for i in ${CHILDS[$1]};do
            walk $i
        done
    }

   walk $1
)

steam steam://rungameid/$1 &
# give steam some time to login and start the game
for i in $(seq 1 30); do
	sleep 1;
	if [ -n "$(pgrep -w SteamChildMonit)" ]; then
		echo "game started after ~$i seconds"
		break
	fi
done

while true; do
	sleep 1
	if [ -z "$(pgrep -w SteamChildMonit)" ]; then
		steam -shutdown
		exit
	fi
done