#!/bin/bash
#203160 tomb raider
#20900 wticher
unset STEAM_CLIENT_CONFIG_FILE
unset STEAMSCRIPT
unset SteamAppId
unset Steam3Master
unset STEAMSCRIPT_VERSION
unset SteamNoOverlayUI
unset SteamTenfoot
unset STEAMVIDEOTOKEN
unset STEAM_RUNTIME
unset SteamAppUser
unset SteamUser
unset SteamStreamingHardwareEncodingNVIDIA
unset SteamGameId
unset SteamStreamingHardwareEncodingIntel
unset SteamLauncherUI
unset SteamStreamingForceWindowedD3D9
unset SteamStreamingMaximumResolution
unset SteamStreamingAllowGameVsync
unset SteamStreaming
unset SteamStreamingHardwareEncodingAMD

if [ -z "$WINEPREFIX" ]; then
	export WINEPREFIX=/usr/local/games/_wine/steam
fi
echo "using WINEPREFIX: $WINEPREFIX"

export XMODIFIERS=''
cd $WINEPREFIX/'drive_c/Program Files/Steam'
#CHKCMD="pgrep -l -w -f '.*steamapps\\common\\.*\.exe.*'"

# FUCK YOU
sed -ri 's/("SkipOfflineModeWarning"\s+)"0"/\1"1"/' $WINEPREFIX/'drive_c/Program Files/Steam/config/loginusers.vdf'

wine Steam.exe steam://rungameid/$1 &
# give steam some time to login and start the game
for i in $(seq 1 30); do
	sleep 1;
	if [ -n "$(pgrep -l -w -f '.*steamapps\\common\\.*\.exe.*')" ]; then
		echo "game started after ~$i seconds"
		break
	fi
done

while true; do
	sleep 1
	if [ -z "$(pgrep -l -w -f '.*steamapps\\common\\.*\.exe.*')" ]; then
		wine Steam.exe -shutdown
		exit
	fi
done
